artifact_location: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/ObjectDetection/YOLO/Poke
  Card Detection/Yolo-Weights/runs/mlflow/0
creation_time: 1719927465224
experiment_id: '0'
last_update_time: 1719927465224
lifecycle_stage: active
name: Default
